minimumReleaseAge: 4320
preferFrozenLockfile: true
blockExoticSubdeps: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.4.1

allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
